### PR TITLE
Support for environment variables in script execution

### PR DESCRIPTION
**Pull request by mefellows**
This PR addresses issue #6, supporting environment variables in the ExecuteCommand template for Powershell scripts only. That is, inline scripts of any sort or cmd scripts will not support the {{.Vars}} template variable.

### CODE REVIEW

**Comment by dylanmei** [comment]
Looking over the code, it seems like this won't work...

    "type": "windows-shell",
    "inline": [
      "add-content C:\\Temp\\Hello.txt -Value 'Hello $env:PACKER_BUILDER_TYPE'"
    ]

But if I packed it into a script it would?

**Comment by mefellows** [comment]
That's correct. I think it should be possible but the escaping gets a bit messy. Currently thinking it might make sense to convert the inline command to base64 and then it should be fairly straightforward to execute as per the script itself. I would also log the un-encoded command to output / UI so that users can see what is actually going to happen instead of a cryptic message. What do you think?

**Comment by dylanmei** [comment]
I've run this PR and it works great for me.

I have some thoughts about the inline stuff but I put them in issue https://github.com/packer-community/packer-windows-plugins/issues/12

**Comment by mefellows** [comment]
Great. If you're happy, then I propose that in the spirit of short-lived branches, we merge this is now and I'll move straight onto addressing #12 which will also address the gap this PR leaves with respect to the original issue #6.

**Comment by dylanmei** [comment]
Totally agree!

**Pull request merged**
